// Rates every level in the three pools (js/levels.js, challenge-levels.js, daily-levels.js) and rewrites
// DIFFICULTY.md. Run after adding or regenerating levels:  node tools/rate.js
// --check  only lists levels that have no rating (exit code 1 if any); changes nothing.
const fs = require('fs');
const path = require('path');
const Engine = require('../js/engine.js');
const D = require('./difficulty.js');
const root = path.join(__dirname, '..');
const POOLS = [['LEVELS', 'levels.js'], ['CHALLENGE_LEVELS', 'challenge-levels.js'], ['DAILY_LEVELS', 'daily-levels.js']];
const load = f => require(path.join(root, 'js', f));
const CHECK = process.argv.includes('--check');

if (CHECK) {
  const missing = POOLS.flatMap(([n, f]) => load(f).map((l, i) => (l.diff ? null : `${n}[${i}]`)).filter(Boolean));
  if (missing.length) { console.log(`${missing.length} level(s) have no difficulty (run node tools/rate.js): ${missing.slice(0, 6).join(', ')}${missing.length > 6 ? ' …' : ''}`); process.exit(1); }
  console.log('Difficulty: every level is rated'); process.exit(0);
}

const pools = {};
for (const [name, file] of POOLS) {
  const levels = load(file).slice();
  levels.forEach((l, i) => {
    const m = D.measure(l, Engine);
    if (!m) throw new Error(`${name}[${i}] could not be solved`);
    l.diff = m.diff; l.dscore = m.dscore;
  });
  pools[name] = levels;
  fs.writeFileSync(path.join(root, 'js', file),
    `// Generated by tools/generate.js — every level was solved by the engine; par = its move count.\n// diff (1–5) and dscore: see tools/difficulty.js.\nconst ${name} = ${JSON.stringify(levels)};\nif (typeof module !== "undefined") module.exports = ${name};\n`);
}

// ── DIFFICULTY.md ──
const count = ls => D.NAMES.map((_, t) => ls.filter(l => l.diff === t + 1).length);
const all = Object.values(pools).flat();
let md = `# Level difficulty

Every level has \`diff\` (tier 1–5) and \`dscore\` (the number behind it), measured by the solver — see \`tools/difficulty.js\`.
\`score = room-making moves + 1.2 × mechanics on the board + 0.08 × par + 0.1 × blocks\`. Tiers:

| Tier | Name | Score |
|---|---|---|
${D.NAMES.map((n, i) => `| ${i + 1} | ${n} | ${i === 0 ? `< ${D.THRESHOLDS[0]}` : i === 4 ? `≥ ${D.THRESHOLDS[3]}` : `${D.THRESHOLDS[i - 1]} – ${D.THRESHOLDS[i] - 0.1}`} |`).join('\n')}

New levels are rated by \`tools/generate.js\` as they are made. After changing a pool by hand, run \`node tools/rate.js\`
(it rewrites this file). Challenges (\`diff\` slider) draw from all three pools by tier.

## Levels per tier

| Pool | ${D.NAMES.join(' | ')} | Total |
|---|${D.NAMES.map(() => '---').join('|')}|---|
${[['Campaign (LEVELS)', pools.LEVELS], ['Challenge pool (CHALLENGE_LEVELS)', pools.CHALLENGE_LEVELS], ['Daily pool (DAILY_LEVELS)', pools.DAILY_LEVELS], ['**All**', all]].map(([n, ls]) => `| ${n} | ${count(ls).join(' | ')} | ${ls.length} |`).join('\n')}

## Campaign, stage by stage (tier of each of the five levels)

| Levels | Stage | Tiers |
|---|---|---|
`;
const game = fs.readFileSync(path.join(root, 'js', 'game.js'), 'utf8');
const stageNames = [...(game.match(/const STAGES = \[([\s\S]*?)\n\];/) || ['', ''])[1].matchAll(/\['([^']+)', '\w+'\]/g)].map(m => m[1]);
for (let s = 0; s * 5 < pools.LEVELS.length; s++) md += `| ${s * 5 + 1}–${s * 5 + 5} | ${stageNames[s] || '?'} | ${pools.LEVELS.slice(s * 5, s * 5 + 5).map(l => l.diff).join(' ')} |\n`;

// Story puzzles: which tier each one is (pool 'hard' = DAILY_LEVELS, otherwise CHALLENGE_LEVELS).
const story = fs.readFileSync(path.join(root, 'js', 'story.js'), 'utf8');
md += `\n## Story puzzles (pool index → tier)\n\n`;
for (const m of story.matchAll(/const (CH\d) = \[([\s\S]*?)\n  \];/g)) {
  const rows = [...m[2].matchAll(/puzzle: (\d+), pool: '(\w+)'[^}]*?title: '([^']*)'/g)].map(p => {
    const l = (p[2] === 'hard' ? pools.DAILY_LEVELS : pools.CHALLENGE_LEVELS)[+p[1]];
    return `${p[3]} (${p[2] === 'hard' ? 'daily' : 'challenge'} #${p[1]}: ${l ? D.NAMES[l.diff - 1] : '?'})`;
  });
  md += `- **${m[1]}**: ${rows.join('; ')}\n`;
}
fs.writeFileSync(path.join(root, 'DIFFICULTY.md'), md);
console.log('rated', all.length, 'levels —', D.NAMES.map((n, i) => `${n} ${count(all)[i]}`).join(', '));
